# Generated by Django 5.2b1 on 2026-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "verbose_name": "Остаток",
                "verbose_name_plural": "Остатки",
            },
        ),
        migrations.AlterModelOptions(
            name="procurementrequest",
            options={
                "verbose_name": "Заявка на закупку",
                "verbose_name_plural": "Заявки на закупку",
            },
        ),
    ]
