# Generated by Django 5.2b1 on 2026-01-10 05:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="пищевая особенность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пищевая особенность",
                "verbose_name_plural": "Пищевые особенности",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "student"),
                            (100, "cook"),
                            (10000, "admin"),
                        ],
                        default=10,
                        unique=True,
                        verbose_name="уровень доступа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="персонал"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="дата регистрации",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ФИО может содержать только буквы, пробелы и дефисы",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s-]+$",
                            )
                        ],
                        verbose_name="фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ФИО может содержать только буквы, пробелы и дефисы",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s-]+$",
                            )
                        ],
                        verbose_name="имя",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ФИО может содержать только буквы, пробелы и дефисы",
                                regex="^[а-яА-ЯёЁa-zA-Z\\s-]+$",
                            )
                        ],
                        verbose_name="отчество",
                    ),
                ),
                (
                    "school_class",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 класс"),
                            (2, "2 класс"),
                            (3, "3 класс"),
                            (4, "4 класс"),
                            (5, "5 класс"),
                            (6, "6 класс"),
                            (7, "7 класс"),
                            (8, "8 класс"),
                            (9, "9 класс"),
                            (10, "10 класс"),
                            (11, "11 класс"),
                        ],
                        null=True,
                        verbose_name="класс в школе",
                    ),
                ),
                (
                    "birthday",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        validators=[users.validators.validate_not_future],
                        verbose_name="дата рождения",
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="попытки входа"
                    ),
                ),
                (
                    "block_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата блокировки"
                    ),
                ),
                (
                    "allergens",
                    models.ManyToManyField(
                        blank=True,
                        to="users.foodfeatures",
                        verbose_name="аллергены",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Группы, к которым принадлежит пользователь.",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="группы",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.role",
                        verbose_name="роль",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Специальные разрешения для пользователя.",
                        related_name="custom_user_set_permissions",
                        to="auth.permission",
                        verbose_name="разрешения пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
