# Generated by Django 5.2b1 on 2026-01-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="allergens",
        ),
        migrations.AddField(
            model_name="user",
            name="food_features",
            field=models.ManyToManyField(
                blank=True,
                to="users.foodfeatures",
                verbose_name="индивидуальные предпочтения",
            ),
        ),
    ]
