# Generated by Django 5.2b1 on 2026-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_allergens_user_food_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="level",
        ),
        migrations.AddField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("student", "ученик"),
                    ("cook", "повар"),
                    ("admin", "администратор"),
                ],
                default="student",
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
