# Generated by Django 5.2b1 on 2026-01-24 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meals_left",
                    models.PositiveIntegerField(
                        default=0, verbose_name="доступных приёмов пищи"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="активен"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к питанию",
                "verbose_name_plural": "Доступы к питанию",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("single", "Разовый платёж"),
                            ("subscription", "Абонемент"),
                        ],
                        max_length=20,
                        verbose_name="тип оплаты",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="сумма")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата оплаты"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="успешно"),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="уникальный код",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ("-created",),
            },
        ),
    ]
