# Generated by Django 5.2b1 on 2026-01-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="особенность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность блюда",
                "verbose_name_plural": "Особенности блюда",
            },
        ),
        migrations.AlterField(
            model_name="dish",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="features",
                to="menu.dishfeatures",
                verbose_name="Особенности блюда",
            ),
        ),
    ]
