# Generated by Django 5.2b1 on 2026-01-12 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_dishfeatures_alter_dish_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breakfastmenu",
            options={
                "verbose_name": "Завтрак",
                "verbose_name_plural": "Завтраки",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="lunchmenu",
            options={"verbose_name": "Обед", "verbose_name_plural": "Обеды"},
        ),
        migrations.RemoveField(
            model_name="breakfastmenu",
            name="pastry",
        ),
        migrations.RemoveField(
            model_name="breakfastmenu",
            name="porridge",
        ),
        migrations.AddField(
            model_name="breakfastmenu",
            name="dish1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_dish1",
                to="menu.dish",
            ),
        ),
        migrations.AddField(
            model_name="breakfastmenu",
            name="dish2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_dish2",
                to="menu.dish",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.IntegerField(verbose_name="количество"),
        ),
    ]
