# Generated by Django 5.2b1 on 2026-01-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu",
            "0003_alter_breakfastmenu_options_alter_dish_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakfastmenu",
            name="dish1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_dish1",
                to="menu.dish",
                verbose_name="первое блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="breakfastmenu",
            name="dish2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_dish2",
                to="menu.dish",
                verbose_name="второе блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="breakfastmenu",
            name="drink1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_drink1",
                to="menu.dish",
                verbose_name="первый напиток",
            ),
        ),
        migrations.AlterField(
            model_name="breakfastmenu",
            name="drink2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="breakfast_drink2",
                to="menu.dish",
                verbose_name="второй напиток",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="drink1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_drink1",
                to="menu.dish",
                verbose_name="первый напиток",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="drink2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_drink2",
                to="menu.dish",
                verbose_name="второй напиток",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_main",
                to="menu.dish",
                verbose_name="основое блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="salad1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_salad1",
                to="menu.dish",
                verbose_name="первый салат",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="salad2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_salad2",
                to="menu.dish",
                verbose_name="второй салат",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="soup1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_soup1",
                to="menu.dish",
                verbose_name="первый суп",
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="soup2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunch_soup2",
                to="menu.dish",
                verbose_name="второй суп",
            ),
        ),
    ]
