# Generated by Django 5.2b1 on 2026-01-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="comment",
            field=models.TextField(default=1, verbose_name="комментарий"),
            preserve_default=False,
        ),
    ]
