# Generated by Django 5.2b1 on 2026-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_rating_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="mark",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                verbose_name="оценка",
            ),
        ),
    ]
